/**
 * AdvancedPDFViewer — pdf-viewer.js
 * ============================================================
 * Three-part advanced PDF library (CSS + JS + HTML)
 * Engine : PDF.js  (loaded via CDN — no bundler needed)
 * Author : Generated by Claude Code
 *
 * Usage:
 *   const viewer = new AdvancedPDFViewer('#my-container', { /* options *\/ });
 *   viewer.loadURL('document.pdf');
 * ============================================================
 */

(function (global) {
  'use strict';

  /* -------------------------------------------------------
     SVG icon helpers — inline so no external icon font needed
  ------------------------------------------------------- */
  const ICONS = {
    menu:       `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>`,
    thumbs:     `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>`,
    outline:    `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="8" y1="6" x2="21" y2="6"/><line x1="8" y1="12" x2="21" y2="12"/><line x1="8" y1="18" x2="21" y2="18"/><line x1="3" y1="6" x2="3.01" y2="6"/><line x1="3" y1="12" x2="3.01" y2="12"/><line x1="3" y1="18" x2="3.01" y2="18"/></svg>`,
    prev:       `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"/></svg>`,
    next:       `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="9 18 15 12 9 6"/></svg>`,
    first:      `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="11 17 6 12 11 7"/><polyline points="18 17 13 12 18 7"/></svg>`,
    last:       `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="13 17 18 12 13 7"/><polyline points="6 17 11 12 6 7"/></svg>`,
    zoomin:     `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/><line x1="11" y1="8" x2="11" y2="14"/><line x1="8" y1="11" x2="14" y2="11"/></svg>`,
    zoomout:    `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/><line x1="8" y1="11" x2="14" y2="11"/></svg>`,
    search:     `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>`,
    rotate_l:   `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="1 4 1 10 7 10"/><path d="M3.51 15a9 9 0 1 0 .49-4"/></svg>`,
    rotate_r:   `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="23 4 23 10 17 10"/><path d="M20.49 15a9 9 0 1 1-.49-4"/></svg>`,
    fullscreen: `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 3 21 3 21 9"/><polyline points="9 21 3 21 3 15"/><line x1="21" y1="3" x2="14" y2="10"/><line x1="3" y1="21" x2="10" y2="14"/></svg>`,
    compress:   `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="4 14 10 14 10 20"/><polyline points="20 10 14 10 14 4"/><line x1="10" y1="14" x2="3" y2="21"/><line x1="21" y1="3" x2="14" y2="10"/></svg>`,
    dark:       `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>`,
    light:      `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>`,
    download:   `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>`,
    upload:     `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>`,
    keyboard:   `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="6" width="20" height="12" rx="2"/><line x1="6" y1="10" x2="6.01" y2="10"/><line x1="10" y1="10" x2="10.01" y2="10"/><line x1="14" y1="10" x2="14.01" y2="10"/><line x1="18" y1="10" x2="18.01" y2="10"/><line x1="8" y1="14" x2="16" y2="14"/></svg>`,
    twopage:    `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="9" height="18" rx="1"/><rect x="13" y="3" width="9" height="18" rx="1"/></svg>`,
    close:      `<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>`,
    chevron:    `<svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 18 15 12 9 6"/></svg>`,
    fit_w:      `<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="18" height="18" rx="2"/><line x1="3" y1="12" x2="21" y2="12"/><polyline points="8 8 3 12 8 16"/><polyline points="16 8 21 12 16 16"/></svg>`,
    pdf_icon:   `<svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/><polyline points="10 9 9 9 8 9"/></svg>`,
  };

  /* -------------------------------------------------------
     Utility — create element
  ------------------------------------------------------- */
  function el(tag, cls, html) {
    const e = document.createElement(tag);
    if (cls) e.className = cls;
    if (html !== undefined) e.innerHTML = html;
    return e;
  }

  function btn(icon, tip, cls) {
    const b = el('button', 'pv-btn' + (cls ? ' ' + cls : ''), ICONS[icon] || icon);
    if (tip) b.setAttribute('data-tip', tip);
    return b;
  }

  /* -------------------------------------------------------
     Default options
  ------------------------------------------------------- */
  const DEFAULTS = {
    darkMode: false,
    sidebarOpen: true,
    sidebarTab: 'thumbs',   // 'thumbs' | 'outline'
    zoom: 'fitWidth',        // number(%) or 'fitWidth'|'fitPage'|'actual'
    rotation: 0,
    workerSrc: 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js',
    cMapUrl:   'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/cmaps/',
    cMapPacked: true,
    renderTextLayer: true,
    thumbSize: 160,
    scrollThreshold: 0.5,
    enableDrop: true,
    enableKeyboard: true,
    onLoad: null,
    onError: null,
    onPageChange: null,
  };

  /* -------------------------------------------------------
     Main class
  ------------------------------------------------------- */
  class AdvancedPDFViewer {
    constructor(containerSelector, options = {}) {
      this.opts = Object.assign({}, DEFAULTS, options);

      // Resolve container
      this.container = typeof containerSelector === 'string'
        ? document.querySelector(containerSelector)
        : containerSelector;

      if (!this.container) throw new Error('PDFViewer: container not found');

      // State
      this.pdfDoc       = null;
      this.currentPage  = 1;
      this.totalPages   = 0;
      this.zoom         = 1.0;
      this.rotation     = this.opts.rotation || 0;
      this.darkMode     = this.opts.darkMode;
      this.sidebarOpen  = this.opts.sidebarOpen;
      this.sidebarTab   = this.opts.sidebarTab;
      this.twoPage      = false;
      this.isFullscreen = false;
      this.searchOpen   = false;
      this.searchQuery  = '';
      this.searchMatches = [];
      this.searchIdx    = -1;
      this._pageTextCache = {};        // pageNum → { items, cumOffsets, joined }
      this.renderQueue  = new Map();   // pageNum → cancel token
      this.thumbQueue   = new Set();
      this.pageHeights  = [];
      this._pdfUrl      = null;
      this._pdfBytes    = null;
      this._shortcutOpen = false;
      this._scrollTimer          = null;
      this._scrollIndicatorTimer = null;
      this._scrollHideTimer      = null;
      this._fsUiTimer            = null;
      this._resizeObs            = null;
      this._pendingZoom  = this.opts.zoom;

      this._build();
      this._bindEvents();
      this._ensurePDFJS();
    }

    /* ---------------------------------------------------
       Build DOM
    --------------------------------------------------- */
    _build() {
      // On mobile, always start with sidebar collapsed so the CSS default
      // (transform: translateX(-110%)) is already in effect on first paint.
      if (window.innerWidth <= 767) this.sidebarOpen = false;

      this.wrap = el('div', 'pdf-viewer-wrap' + (this.darkMode ? ' dark' : ''));

      // ---- Toolbar ----
      this.wrap.appendChild(this._buildToolbar());

      // ---- Body ----
      const body = el('div', 'pv-body');

      // Sidebar
      body.appendChild(this._buildSidebar());

      // Backdrop — darkens viewport when sidebar is open as a drawer on mobile
      this.sidebarBackdrop = el('div', 'pv-sidebar-backdrop');
      this.sidebarBackdrop.addEventListener('click', () => this.toggleSidebar());
      body.appendChild(this.sidebarBackdrop);

      // Viewport
      this.viewport = el('div', 'pv-viewport');

      // Empty state
      this.emptyState = el('div', 'pv-empty');
      this.emptyState.innerHTML = `
        <div class="pv-empty-icon">${ICONS.pdf_icon}</div>
        <div class="pv-empty-title">No PDF loaded</div>
        <div class="pv-empty-sub">Drop a PDF here or click Open to load a file</div>
        <label class="pv-drop-zone-label">
          ${ICONS.upload} Open PDF file
          <input type="file" accept="application/pdf" style="display:none" id="pv-file-input-${Date.now()}">
        </label>`;
      this._fileInput = this.emptyState.querySelector('input[type=file]');
      this.viewport.appendChild(this.emptyState);

      // Loading overlay
      this.loadingEl = el('div', 'pv-loading hidden');
      this.loadingEl.innerHTML = `
        <div class="pv-spinner"></div>
        <div class="pv-loading-text">Loading PDF…</div>
        <div class="pv-progress-bar-wrap"><div class="pv-progress-bar"></div></div>`;
      this._progressBar = this.loadingEl.querySelector('.pv-progress-bar');
      this._loadingText = this.loadingEl.querySelector('.pv-loading-text');
      this.viewport.appendChild(this.loadingEl);

      // Drop overlay
      this.dropOverlay = el('div', 'pv-drop-overlay', `${ICONS.upload} Drop PDF here`);
      this.viewport.appendChild(this.dropOverlay);

      // Pages container
      this.pagesContainer = el('div', 'pv-pages-container');
      this.viewport.appendChild(this.pagesContainer);

      // Toast container
      this.toastWrap = el('div', 'pv-toast-wrap');
      this.viewport.appendChild(this.toastWrap);

      // Scroll indicator — card-tab that slides from the right edge.
      // Appended to this.wrap (position:relative), NOT this.viewport, so it
      // stays fixed relative to the viewer and doesn't scroll with the content.
      this.scrollIndicator = el('div', 'pv-scroll-indicator');
      this._siText = el('span', 'pv-si-text');
      const siGrip = el('span', 'pv-si-grip');
      // 6 dots (2 cols × 3 rows) — visual grip handle
      for (let i = 0; i < 6; i++) siGrip.appendChild(el('span', 'pv-si-dot'));
      this.scrollIndicator.appendChild(this._siText);
      this.scrollIndicator.appendChild(siGrip);

      // Context menu
      this.ctxMenu = el('div', 'pv-context-menu');
      this.ctxMenu.innerHTML = `
        <div class="pv-ctx-item" data-action="copy">${ICONS.search} Copy text</div>`;
      document.body.appendChild(this.ctxMenu);

      // Shortcuts overlay
      this.shortcutOverlay = el('div', 'pv-shortcut-overlay');
      this.shortcutOverlay.innerHTML = `
        <div class="pv-shortcut-box">
          <h3>${ICONS.keyboard} Keyboard Shortcuts</h3>
          <div class="pv-shortcut-grid">
            <span class="pv-shortcut-key">← / →</span><span class="pv-shortcut-desc">Prev / Next page</span>
            <span class="pv-shortcut-key">Home / End</span><span class="pv-shortcut-desc">First / Last page</span>
            <span class="pv-shortcut-key">Ctrl + F</span><span class="pv-shortcut-desc">Search</span>
            <span class="pv-shortcut-key">Ctrl + +/−</span><span class="pv-shortcut-desc">Zoom in / out</span>
            <span class="pv-shortcut-key">Ctrl + 0</span><span class="pv-shortcut-desc">Fit width</span>
            <span class="pv-shortcut-key">Ctrl + 1</span><span class="pv-shortcut-desc">Actual size</span>
            <span class="pv-shortcut-key">R</span><span class="pv-shortcut-desc">Rotate right</span>
            <span class="pv-shortcut-key">Shift + R</span><span class="pv-shortcut-desc">Rotate left</span>
            <span class="pv-shortcut-key">F</span><span class="pv-shortcut-desc">Fullscreen</span>
            <span class="pv-shortcut-key">D</span><span class="pv-shortcut-desc">Dark mode</span>
            <span class="pv-shortcut-key">S</span><span class="pv-shortcut-desc">Toggle sidebar</span>
            <span class="pv-shortcut-key">T</span><span class="pv-shortcut-desc">Two-page view</span>
            <span class="pv-shortcut-key">?</span><span class="pv-shortcut-desc">This help</span>
            <span class="pv-shortcut-key">Esc</span><span class="pv-shortcut-desc">Close / exit</span>
          </div>
          <button class="pv-btn" id="pv-close-shortcuts" style="margin-top:16px;width:auto;padding:0 12px;">Close</button>
        </div>`;
      this.wrap.appendChild(this.shortcutOverlay);

      body.appendChild(this.viewport);
      this.wrap.appendChild(body);

      // Status bar
      this.wrap.appendChild(this._buildStatusBar());

      // Bottom bar — fixed to screen bottom on mobile (position:fixed in CSS)
      this.bottomBar = el('div', 'pv-bottom-bar');
      this.wrap.appendChild(this.bottomBar);

      // Scroll indicator — lives in this.wrap (position:relative) so it stays
      // fixed relative to the viewer, not the scrollable content.
      this.wrap.appendChild(this.scrollIndicator);

      this.container.appendChild(this.wrap);

      // Apply sidebar initial state
      if (!this.sidebarOpen) this.sidebar.classList.add('hidden');
    }

    _buildToolbar() {
      const tb = el('div', 'pv-toolbar');
      this.toolbar = tb;

      // ── File group (hamburger · open · filename) — always top ────────────
      const g1 = el('div', 'pv-toolbar-group pv-tg-file');
      this.btnSidebar = btn('menu', 'Toggle sidebar');
      this.btnSidebar.classList.toggle('active', this.sidebarOpen);
      this.btnOpen    = btn('upload', 'Open PDF');
      this.filenameEl = el('span', 'pv-filename', '');
      g1.append(this.btnSidebar, this.btnOpen, this.filenameEl);
      tb.appendChild(g1);
      tb.appendChild(el('div', 'pv-toolbar-sep pv-sep-after-file'));

      // ── Navigation group ── (moves to bottom bar on mobile) ──────────────
      const gnav = el('div', 'pv-toolbar-group pv-tg-nav');
      this.btnFirst  = btn('first', 'First page');
      this.btnPrev   = btn('prev',  'Previous page (←)');
      this.pageNav   = el('div', 'pv-page-nav');
      this.pageInput = el('input', 'pv-page-input');
      this.pageInput.type = 'text';
      this.pageInput.value = '1';
      this.pageInput.setAttribute('aria-label', 'Page number');
      const pageSep = el('span', 'pv-page-sep', '/');
      this.pageTotalEl = el('span', 'pv-page-total', '0');
      this.pageNav.append(this.pageInput, pageSep, this.pageTotalEl);
      this.btnNext = btn('next', 'Next page (→)');
      this.btnLast = btn('last', 'Last page');
      gnav.append(this.btnFirst, this.btnPrev, this.pageNav, this.btnNext, this.btnLast);

      // ── Zoom group ── (moves to bottom bar on mobile) ─────────────────────
      const gzoom = el('div', 'pv-toolbar-group pv-zoom-wrap');
      this.btnZoomOut = btn('zoomout', 'Zoom out (Ctrl+−)');
      this.zoomSelect = el('select', 'pv-zoom-select');
      [
        ['fitWidth','Fit Width'],['fitPage','Fit Page'],['actual','Actual Size'],
        ['50','50%'],['75','75%'],['100','100%'],['125','125%'],
        ['150','150%'],['175','175%'],['200','200%'],['300','300%'],['400','400%'],
      ].forEach(([v, t]) => {
        const o = document.createElement('option');
        o.value = v; o.textContent = t;
        this.zoomSelect.appendChild(o);
      });
      this.btnZoomIn = btn('zoomin', 'Zoom in (Ctrl++)');
      gzoom.append(this.btnZoomOut, this.zoomSelect, this.btnZoomIn);

      // Anchor 1 — desktop: gnav + gzoom live before search bar
      this._tbAnchor1 = el('span', 'pv-tb-anchor');
      tb.appendChild(this._tbAnchor1);
      tb.appendChild(el('div', 'pv-toolbar-sep'));

      // ── Search bar (inline, expands when open) — always top ──────────────
      this.searchBar = el('div', 'pv-search-bar');
      this.searchInput = el('input', 'pv-search-input');
      this.searchInput.type = 'text';
      this.searchInput.placeholder = 'Search…';
      this.searchCountEl = el('span', 'pv-search-count', '');
      const searchPrev  = btn('prev',  'Prev match');
      searchPrev.id     = 'pv-search-prev';
      const searchNextBtn = btn('next', 'Next match');
      searchNextBtn.id  = 'pv-search-next';
      const searchClose = btn('close', 'Close search');
      searchClose.id    = 'pv-search-close';
      const srchIcon = el('span', ''); srchIcon.innerHTML = ICONS.search;
      this.searchBar.append(srchIcon, this.searchInput, this.searchCountEl,
        searchPrev, searchNextBtn, searchClose);
      tb.appendChild(this.searchBar);
      this.btnSearch = btn('search', 'Search (Ctrl+F)');
      tb.appendChild(this.btnSearch);

      // ── Extra tools (rotate · two-page · fit-width) ── (moves to bottom bar)
      const gtools = el('div', 'pv-toolbar-group pv-tg-tools');
      this.btnRotL    = btn('rotate_l', 'Rotate left (Shift+R)');
      this.btnRotR    = btn('rotate_r', 'Rotate right (R)');
      this.btnTwoPage = btn('twopage',  'Two-page view (T)');
      this.btnFitW    = btn('fit_w',    'Fit width (Ctrl+0)');
      gtools.append(this.btnRotL, this.btnRotR, this.btnTwoPage, this.btnFitW);

      // ── Keyboard btn ── (moves to bottom bar on mobile) ──────────────────
      this.btnKeyboard = btn('keyboard', 'Keyboard shortcuts (?)');

      // Anchor 2 — desktop: gtools + btnKeyboard live after search button
      tb.appendChild(el('div', 'pv-toolbar-sep'));
      this._tbAnchor2 = el('span', 'pv-tb-anchor');
      tb.appendChild(this._tbAnchor2);

      // ── Spacer + Right tools (dark · fullscreen) — always top ────────────
      tb.appendChild(el('div', 'pv-toolbar-spacer'));
      const gright = el('div', 'pv-toolbar-group pv-tg-right');
      this.btnDark       = btn(this.darkMode ? 'light' : 'dark', 'Toggle dark mode (D)');
      this.btnFullscreen = btn('fullscreen', 'Fullscreen (F)');
      gright.append(this.btnDark, this.btnFullscreen);
      tb.appendChild(gright);

      // Groups that travel to bottom bar on mobile
      this._bbGroup1 = [gnav, gzoom];               // inserted before search (anchor 1)
      this._bbGroup2 = [gtools, this.btnKeyboard];   // inserted after search (anchor 2)

      this._searchPrev  = searchPrev;
      this._searchNext  = searchNextBtn;
      this._searchClose = searchClose;

      return tb;
    }

    _buildSidebar() {
      this.sidebar = el('div', 'pv-sidebar' + (this.sidebarOpen ? '' : ' hidden'));

      // Tabs
      const tabs = el('div', 'pv-sidebar-tabs');
      this.tabThumbs   = el('button', 'pv-sidebar-tab' + (this.sidebarTab === 'thumbs' ? ' active' : ''),
        `${ICONS.thumbs} Thumbs`);
      this.tabOutline  = el('button', 'pv-sidebar-tab' + (this.sidebarTab === 'outline' ? ' active' : ''),
        `${ICONS.outline} Outline`);
      tabs.append(this.tabThumbs, this.tabOutline);
      this.sidebar.appendChild(tabs);

      // Panels
      this.thumbsPanel  = el('div', 'pv-sidebar-panel' + (this.sidebarTab === 'thumbs' ? ' active' : ''));
      this.thumbsGrid   = el('div', 'pv-thumbs-grid');
      this.thumbsPanel.appendChild(this.thumbsGrid);

      this.outlinePanel = el('div', 'pv-sidebar-panel' + (this.sidebarTab === 'outline' ? ' active' : ''));
      this.outlineList  = el('ul', 'pv-outline-list');
      this.outlinePanel.appendChild(this.outlineList);

      this.sidebar.append(this.thumbsPanel, this.outlinePanel);
      return this.sidebar;
    }

    _buildStatusBar() {
      this.statusbar = el('div', 'pv-statusbar');
      this.statusbarPage  = el('span', 'pv-statusbar-item', '');
      this.statusbarZoom  = el('span', 'pv-statusbar-item', '');
      this.statusbarSize  = el('span', 'pv-statusbar-item', '');
      this.statusbarMode  = el('span', 'pv-statusbar-item', '');
      this.statusbar.append(
        this.statusbarPage,
        el('span', 'pv-statusbar-spacer'),
        this.statusbarZoom,
        this.statusbarSize,
        this.statusbarMode,
      );
      return this.statusbar;
    }

    /* ---------------------------------------------------
       PDF.js loader
    --------------------------------------------------- */
    _ensurePDFJS() {
      if (window.pdfjsLib) { this._initWorker(); return; }
      const script = document.createElement('script');
      script.src = 'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';
      script.onload = () => this._initWorker();
      script.onerror = () => this._showError('Failed to load PDF.js from CDN');
      document.head.appendChild(script);
    }

    _initWorker() {
      if (!window.pdfjsLib) return;
      window.pdfjsLib.GlobalWorkerOptions.workerSrc = this.opts.workerSrc;
    }

    /* ---------------------------------------------------
       Public API — load
    --------------------------------------------------- */
    loadURL(url) {
      this._pdfUrl   = url;
      this._pdfBytes = null;
      const name = url.split('/').pop().split('?')[0];
      this._load({ url, cMapUrl: this.opts.cMapUrl, cMapPacked: this.opts.cMapPacked }, name);
    }

    loadFile(file) {
      const reader = new FileReader();
      reader.onload = (e) => {
        this._pdfBytes = e.target.result;
        this._pdfUrl   = null;
        this._load({ data: e.target.result, cMapUrl: this.opts.cMapUrl, cMapPacked: this.opts.cMapPacked }, file.name);
      };
      reader.readAsArrayBuffer(file);
    }

    loadArrayBuffer(buffer, name) {
      this._pdfBytes = buffer;
      this._pdfUrl   = null;
      this._load({ data: buffer, cMapUrl: this.opts.cMapUrl, cMapPacked: this.opts.cMapPacked }, name || 'document.pdf');
    }

    async _load(src, name) {
      if (!window.pdfjsLib) {
        // Wait for PDF.js
        await new Promise(r => setTimeout(r, 800));
        if (!window.pdfjsLib) { this._showError('PDF.js not available'); return; }
        this._initWorker();
      }

      this._showLoading(true);
      this._setProgress(5);
      this._clearPages();
      this.pdfDoc = null;

      try {
        const loadTask = pdfjsLib.getDocument(src);
        loadTask.onProgress = (p) => {
          if (p.total > 0) this._setProgress(Math.round((p.loaded / p.total) * 80));
        };

        this.pdfDoc = await loadTask.promise;
        this.totalPages = this.pdfDoc.numPages;
        this.currentPage = 1;
        this.pageHeights = [];

        // UI
        this.pageTotalEl.textContent = this.totalPages;
        this.pageInput.value = 1;
        this._setProgress(85);
        this.filenameEl.textContent = name || '';

        // Render thumbnails
        this._buildThumbsGrid();

        // Load outline
        this._loadOutline();

        // Apply initial zoom
        await this._applyInitialZoom();

        this._setProgress(100);
        this._showLoading(false);
        this.emptyState.style.display = 'none';

        this._updateNavButtons();
        this._updateStatusBar();

        if (typeof this.opts.onLoad === 'function') this.opts.onLoad(this.pdfDoc);
        this.toast(`Loaded: ${name}`);
      } catch (err) {
        this._showError('Failed to load PDF: ' + err.message);
        if (typeof this.opts.onError === 'function') this.opts.onError(err);
      }
    }

    /* ---------------------------------------------------
       Zoom management
    --------------------------------------------------- */
    async _applyInitialZoom() {
      const z = this._pendingZoom || this.opts.zoom;
      if (z === 'fitWidth' || z === 'fitPage' || z === 'actual') {
        await this._calcFitZoom(z);
      } else if (typeof z === 'number' || !isNaN(parseFloat(z))) {
        this.zoom = parseFloat(z) / 100;
      } else {
        await this._calcFitZoom('fitWidth');
      }
      this._syncZoomSelect();
      await this._renderAllPages();
    }

    async _calcFitZoom(mode) {
      if (!this.pdfDoc) return;
      const page = await this.pdfDoc.getPage(1);
      const vp   = page.getViewport({ scale: 1, rotation: this.rotation });
      const availW = this.viewport.clientWidth - 48;
      const availH = this.viewport.clientHeight - 48;

      if (mode === 'fitWidth') {
        this.zoom = availW / vp.width;
      } else if (mode === 'fitPage') {
        this.zoom = Math.min(availW / vp.width, availH / vp.height);
      } else {
        this.zoom = 1;
      }
      this.zoom = Math.max(0.1, Math.min(this.zoom, 5));
    }

    async setZoom(value) {
      // Track the current zoom MODE so the ResizeObserver knows whether to re-fit
      this._zoomMode = (value === 'fitWidth' || value === 'fitPage' || value === 'actual')
        ? value : 'manual';

      if (value === 'fitWidth' || value === 'fitPage' || value === 'actual') {
        await this._calcFitZoom(value === 'actual' ? 'actual' : value);
      } else {
        this.zoom = Math.max(0.1, Math.min(parseFloat(value) / 100, 5));
      }
      this._syncZoomSelect();
      await this._renderAllPages();
      this._updateStatusBar();
    }

    _syncZoomSelect() {
      const pct = Math.round(this.zoom * 100).toString();
      const exact = this.zoomSelect.querySelector(`option[value="${pct}"]`);
      if (exact) {
        this.zoomSelect.value = pct;
      } else {
        // No preset matches — show the real percentage as a temporary custom option
        // so the dropdown never silently resets to "Fit Width"
        let custom = this.zoomSelect.querySelector('option.pv-zoom-custom');
        if (!custom) {
          custom = document.createElement('option');
          custom.className = 'pv-zoom-custom';
          this.zoomSelect.insertBefore(custom, this.zoomSelect.firstChild);
        }
        custom.value = pct;
        custom.textContent = pct + '%';
        this.zoomSelect.value = pct;
      }
    }

    async zoomIn() {
      this._zoomMode = 'manual';
      this.zoom = Math.min(this.zoom * 1.25, 4.0);
      this._syncZoomSelect();
      this._updateStatusBar();
      this._applyZoomScaleHint();
      this._scheduleRender();
    }
    async zoomOut() {
      this._zoomMode = 'manual';
      this.zoom = Math.max(this.zoom * 0.8, 0.1);
      this._syncZoomSelect();
      this._updateStatusBar();
      this._applyZoomScaleHint();
      this._scheduleRender();
    }

    _applyZoomScaleHint() {
      if (!this._renderedZoom) return;
      const ratio = this.zoom / this._renderedZoom;
      this.pagesContainer.style.transformOrigin = 'top center';
      this.pagesContainer.style.willChange      = 'transform';
      this.pagesContainer.style.transform       = `scale(${ratio})`;
    }

    _scheduleRender() {
      clearTimeout(this._renderTimer);
      this._renderTimer = setTimeout(() => {
        this.pagesContainer.style.transform       = '';
        this.pagesContainer.style.transformOrigin = '';
        this.pagesContainer.style.willChange      = '';
        this._reRenderPagesInPlace();   // no blank flash for button zoom either
      }, 250);
    }

    /* ---------------------------------------------------
       Page rendering
    --------------------------------------------------- */
    // Re-render after a zoom change WITHOUT clearing pages first.
    // Each existing canvas stays visible until its replacement finishes — no blank flash.
    //
    // Split into three methods so _onTouchEnd can call them across two animation frames
    // to eliminate the brief jump seen when clearing the CSS scale and correcting scroll:
    //   1. _updatePageDimensions() — sync, safe to call while CSS transform is still active
    //   2. _triggerReRender()      — re-wires observer and starts rendering
    //   3. _reRenderPagesInPlace() — convenience wrapper used by button / wheel zoom

    // Step 1: Resize every page container to the current zoom. Does NOT touch the CSS
    // transform or the scroll position, so it can run while the pinch scale is still live.
    _updatePageDimensions() {
      if (!this.pdfDoc) return;
      this._renderedZoom = this.zoom;

      this.pagesContainer.querySelectorAll('.pv-page-wrap').forEach(w => {
        if (w._renderTask) { try { w._renderTask.cancel(); } catch (_) {} }
        w._rendered  = false;
        w._rendering = false;

        // Update stored viewport to new zoom
        w._vp = w._page.getViewport({ scale: this.zoom, rotation: this.rotation });

        // Resize the canvas-wrap container so layout adjusts immediately
        const cw = w.querySelector('.pv-page-canvas-wrap');
        if (cw) {
          cw.style.width  = w._vp.width  + 'px';
          cw.style.height = w._vp.height + 'px';
        }
        // Stretch the existing canvas to fill its new container so old content
        // looks naturally scaled instead of misaligned while the new render arrives.
        if (w._canvas) {
          w._canvas.style.width  = w._vp.width  + 'px';
          w._canvas.style.height = w._vp.height + 'px';
        }
        if (w._textLayer) {
          w._textLayer.style.width  = w._vp.width  + 'px';
          w._textLayer.style.height = w._vp.height + 'px';
        }
        this.pageHeights[parseInt(w.dataset.page)] = w._vp.height;
      });
    }

    // Step 2: Re-wire the IntersectionObserver and eagerly render the visible pages.
    _triggerReRender() {
      if (this._ioObserver) this._ioObserver.disconnect();
      this._ioObserver = null;
      this._lazyRender();

      const lo = Math.max(1, this.currentPage - 1);
      const hi = Math.min(this.totalPages, this.currentPage + 1);
      for (let i = lo; i <= hi; i++) {
        const w = this.pagesContainer.querySelector(`.pv-page-wrap[data-page="${i}"]`);
        if (w) this._renderPage(w);
      }
    }

    // Step 3: Convenience wrapper used by button zoom and wheel zoom.
    async _reRenderPagesInPlace(targetScrollLeft, targetScrollTop) {
      if (!this.pdfDoc) return;
      this._updatePageDimensions();

      // Apply corrected scroll position BEFORE lazy render wires up
      if (targetScrollLeft !== undefined) {
        this.viewport.scrollLeft = targetScrollLeft;
        this.viewport.scrollTop  = targetScrollTop;
      }

      this._triggerReRender();
    }

    async _renderAllPages() {
      if (!this.pdfDoc) return;
      this._renderedZoom = this.zoom;
      this._clearPages();
      this.pageHeights = [];

      for (let i = 1; i <= this.totalPages; i++) {
        const wrap = await this._createPageWrap(i);
        this.pagesContainer.appendChild(wrap);
      }

      // Lazily render pages in viewport
      this._lazyRender();
    }

    async _createPageWrap(pageNum) {
      const page = await this.pdfDoc.getPage(pageNum);
      const vp   = page.getViewport({ scale: this.zoom, rotation: this.rotation });

      const wrap      = el('div', 'pv-page-wrap');
      wrap.dataset.page = pageNum;

      const canvasWrap = el('div', 'pv-page-canvas-wrap');
      canvasWrap.style.width  = vp.width  + 'px';
      canvasWrap.style.height = vp.height + 'px';

      // Placeholder canvas (grey)
      const ph = el('canvas', 'pv-page-canvas');
      ph.width  = vp.width;
      ph.height = vp.height;
      const phCtx = ph.getContext('2d');
      phCtx.fillStyle = this.darkMode ? '#3a3a3a' : '#f5f5f5';
      phCtx.fillRect(0, 0, ph.width, ph.height);

      canvasWrap.appendChild(ph);

      // Text layer — transparent spans for text selection only
      if (this.opts.renderTextLayer) {
        const textLayer = el('div', 'pv-text-layer');
        textLayer.style.width  = vp.width  + 'px';
        textLayer.style.height = vp.height + 'px';
        canvasWrap.appendChild(textLayer);
        wrap._textLayer = textLayer;
      }

      // Highlight layer — separate overlay for search highlights (never touches text layer)
      const hlLayer = el('div', 'pv-highlight-layer');
      canvasWrap.appendChild(hlLayer);
      wrap._hlLayer    = hlLayer;
      wrap._textItems  = null;   // filled by _renderTextLayer

      wrap._page      = page;
      wrap._vp        = vp;
      wrap._canvas    = ph;
      wrap._rendered  = false;
      wrap._rendering = false;

      canvasWrap.style.cursor = 'default';
      wrap.appendChild(canvasWrap);

      // Page label
      const lbl = el('div', 'pv-page-label', `Page ${pageNum}`);
      wrap.appendChild(lbl);

      this.pageHeights[pageNum] = vp.height;
      return wrap;
    }

    async _renderPage(wrap) {
      if (wrap._rendered || wrap._rendering) return;
      wrap._rendering = true;

      const page = wrap._page;
      const vp   = wrap._vp;

      // Create real canvas
      const canvas = el('canvas', 'pv-page-canvas');
      canvas.width  = vp.width;
      canvas.height = vp.height;

      const ctx = canvas.getContext('2d');
      const renderCtx = { canvasContext: ctx, viewport: vp };

      try {
        const task = page.render(renderCtx);
        wrap._renderTask = task;
        await task.promise;

        // Swap placeholder
        wrap._canvas.replaceWith(canvas);
        wrap._canvas  = canvas;
        wrap._rendered = true;

        // Text layer
        if (this.opts.renderTextLayer && wrap._textLayer) {
          await this._renderTextLayer(page, vp, wrap._textLayer);
          // Re-apply search highlights if active
          if (this.searchQuery) this._highlightInPage(wrap);
        }
      } catch (e) {
        if (e.name !== 'RenderingCancelledException') console.warn('Render error:', e);
      }
      wrap._rendering = false;
    }

    async _renderTextLayer(page, vp, container) {
      container.innerHTML = '';
      // PDF.js 3.x requires --scale-factor on the container
      container.style.setProperty('--scale-factor', vp.scale);
      // Use textContentSource (stream) — textContent param is deprecated in 3.x
      const textContentSource = page.streamTextContent();
      const renderTask = pdfjsLib.renderTextLayer({
        textContentSource,
        container,
        viewport: vp,
      });
      await renderTask.promise;
    }

    _lazyRender() {
      if (!this._ioObserver) {
        const io = new IntersectionObserver((entries) => {
          entries.forEach(entry => {
            if (entry.isIntersecting) {
              this._renderPage(entry.target.closest('.pv-page-wrap'));
            }
          });
        }, { root: this.viewport, rootMargin: '200px' });

        this._ioObserver = io;
      }

      this.pagesContainer.querySelectorAll('.pv-page-wrap').forEach(w => {
        const canvas = w.querySelector('.pv-page-canvas-wrap');
        if (canvas) this._ioObserver.observe(canvas);
      });
    }

    _clearPages() {
      if (this._ioObserver) this._ioObserver.disconnect();
      this.pagesContainer.innerHTML = '';
    }

    /* ---------------------------------------------------
       Navigation
    --------------------------------------------------- */
    goToPage(num, smooth = true) {
      if (!this.pdfDoc) return;
      num = Math.max(1, Math.min(num, this.totalPages));
      this.currentPage = num;
      this.pageInput.value = num;

      const wrap = this.pagesContainer.querySelector(`.pv-page-wrap[data-page="${num}"]`);
      if (wrap) {
        wrap.scrollIntoView({ behavior: smooth ? 'smooth' : 'auto', block: 'start' });
      }

      this._updateNavButtons();
      this._updateStatusBar();
      this._highlightActiveThumb(num);

      // On mobile: auto-close the sidebar drawer after navigating to a page
      if (this.sidebarOpen && this._isMobile()) {
        this.toggleSidebar();
      }

      if (typeof this.opts.onPageChange === 'function') this.opts.onPageChange(num, this.totalPages);
    }

    nextPage() { this.goToPage(this.currentPage + (this.twoPage ? 2 : 1)); }
    prevPage() { this.goToPage(this.currentPage - (this.twoPage ? 2 : 1)); }
    firstPage(){ this.goToPage(1); }
    lastPage() { this.goToPage(this.totalPages); }

    _updateNavButtons() {
      this.btnFirst.disabled = this.currentPage <= 1;
      this.btnPrev.disabled  = this.currentPage <= 1;
      this.btnNext.disabled  = this.currentPage >= this.totalPages;
      this.btnLast.disabled  = this.currentPage >= this.totalPages;
    }

    /* ---------------------------------------------------
       Scroll → current page tracker
    --------------------------------------------------- */
    _onViewportScroll() {
      // Show the page pill immediately — no debounce needed for visual feedback
      this._showScrollIndicator();

      clearTimeout(this._scrollTimer);
      this._scrollTimer = setTimeout(() => {
        const wraps = this.pagesContainer.querySelectorAll('.pv-page-wrap');
        const vpTop  = this.viewport.scrollTop;
        const vpH    = this.viewport.clientHeight;

        let best = 1, bestVis = -1;
        wraps.forEach(w => {
          const r = w.getBoundingClientRect();
          const parentR = this.viewport.getBoundingClientRect();
          const relTop = r.top - parentR.top;
          const relBot = r.bottom - parentR.top;
          const vis = Math.min(relBot, vpH) - Math.max(relTop, 0);
          if (vis > bestVis) { bestVis = vis; best = parseInt(w.dataset.page); }
        });

        if (best !== this.currentPage) {
          this.currentPage = best;
          this.pageInput.value = best;
          this._updateNavButtons();
          this._updateStatusBar();
          this._highlightActiveThumb(best);
          // Refresh indicator text after page number is confirmed
          this._updateScrollIndicatorText();
          if (typeof this.opts.onPageChange === 'function') this.opts.onPageChange(best, this.totalPages);
        }
      }, 80);
    }

    // Show/reposition the scroll indicator immediately on scroll.
    _showScrollIndicator() {
      if (!this.pdfDoc || !this.totalPages) return;
      const si = this.scrollIndicator;
      const vp = this.viewport;

      // Cancel any pending hide
      clearTimeout(this._scrollIndicatorTimer);
      clearTimeout(this._scrollHideTimer);

      // Step 1: make the element part of layout (display:flex) so offsetHeight works
      si.style.display = 'flex';

      // Step 2: position based on scroll progress
      const scrollH = vp.scrollHeight - vp.clientHeight;
      if (scrollH > 0) {
        const progress    = vp.scrollTop / scrollH;
        const indH        = si.offsetHeight || 40;
        const vpTopInWrap = this._vpTopInWrap();
        const maxTravel   = vp.clientHeight - indH - 16;
        si.style.top      = Math.round(vpTopInWrap + 8 + progress * Math.max(0, maxTravel)) + 'px';
      }
      this._siText.textContent = `${this.currentPage} / ${this.totalPages}`;

      // Step 3: trigger CSS fade-in in the next frame (display must be set first)
      requestAnimationFrame(() => si.classList.add('visible'));

      // Step 4: schedule hide after 1.5s idle
      this._scrollIndicatorTimer = setTimeout(() => this._hideScrollIndicator(), 1500);
    }

    // Fade out then set display:none — the only reliable way to suppress it on Android.
    _hideScrollIndicator() {
      const si = this.scrollIndicator;
      si.classList.remove('visible');           // triggers CSS fade-out (0.2s)
      clearTimeout(this._scrollHideTimer);
      this._scrollHideTimer = setTimeout(() => {
        // Only hide if .visible wasn't re-added while we were waiting
        if (!si.classList.contains('visible') && !si.classList.contains('dragging')) {
          si.style.display = 'none';
        }
      }, 220);                                   // slightly longer than 0.2s transition
    }

    // Update indicator text only (called after debounce confirms new page number).
    _updateScrollIndicatorText() {
      if (!this.pdfDoc || !this.totalPages) return;
      this._siText.textContent = `${this.currentPage} / ${this.totalPages}`;
    }

    /* ---------------------------------------------------
       Scroll-indicator drag
    --------------------------------------------------- */
    _bindScrollIndicatorDrag() {
      const si  = this.scrollIndicator;
      const vp  = this.viewport;
      let dragging    = false;
      let startY      = 0;
      let startScroll = 0;

      const getClientY = e => e.touches ? e.touches[0].clientY : e.clientY;

      const onStart = (e) => {
        dragging    = true;
        startY      = getClientY(e);
        startScroll = vp.scrollTop;
        si.classList.add('dragging');
        // Keep indicator visible the whole time — cancel the auto-hide timer
        clearTimeout(this._scrollIndicatorTimer);
        e.preventDefault();
        e.stopPropagation();
      };

      const onMove = (e) => {
        if (!dragging) return;
        e.preventDefault();

        const dy      = getClientY(e) - startY;
        const scrollH = vp.scrollHeight - vp.clientHeight;
        const indH    = si.offsetHeight || 40;
        // Track height = viewport height minus pill height minus top/bottom margins
        const trackH  = Math.max(1, vp.clientHeight - indH - 16);
        // Map drag pixels → scroll pixels
        const newScroll = startScroll + (dy / trackH) * scrollH;
        vp.scrollTop = Math.max(0, Math.min(scrollH, newScroll));

        // Reposition pill to match new scroll (without showing the slide-in animation)
        const progress = vp.scrollTop / scrollH;
        const top      = this._vpTopInWrap() + 8 + progress * trackH;
        si.style.top   = Math.round(top) + 'px';
        this._siText.textContent = `${this.currentPage} / ${this.totalPages}`;
      };

      const onEnd = () => {
        if (!dragging) return;
        dragging = false;
        si.classList.remove('dragging');
        // Start the normal auto-hide countdown from this moment
        clearTimeout(this._scrollIndicatorTimer);
        this._scrollIndicatorTimer = setTimeout(() => this._hideScrollIndicator(), 1500);
      };

      si.addEventListener('mousedown',  onStart);
      si.addEventListener('touchstart', onStart, { passive: false });
      document.addEventListener('mousemove',  onMove);
      document.addEventListener('touchmove',  onMove, { passive: false });
      document.addEventListener('mouseup',    onEnd);
      document.addEventListener('touchend',   onEnd);
    }

    // Returns the distance (px) from the top of this.wrap to the top of this.viewport.
    _vpTopInWrap() {
      const vpRect   = this.viewport.getBoundingClientRect();
      const wrapRect = this.wrap.getBoundingClientRect();
      return vpRect.top - wrapRect.top;
    }

    /* ---------------------------------------------------
       Rotation
    --------------------------------------------------- */
    async rotate(delta) {
      this.rotation = ((this.rotation + delta) % 360 + 360) % 360;
      // Re-get viewports with new rotation
      const wraps = this.pagesContainer.querySelectorAll('.pv-page-wrap');
      wraps.forEach(w => {
        w._rendered  = false;
        w._rendering = false;
        w._vp = w._page.getViewport({ scale: this.zoom, rotation: this.rotation });
        const cw = w.querySelector('.pv-page-canvas-wrap');
        if (cw) { cw.style.width = w._vp.width + 'px'; cw.style.height = w._vp.height + 'px'; }
        const c = w._canvas;
        if (c) { c.width = w._vp.width; c.height = w._vp.height; }
      });
      await this._renderAllPages();
      this.toast(`Rotated ${delta > 0 ? 'right' : 'left'} → ${this.rotation}°`);
    }

    /* ---------------------------------------------------
       Search
    --------------------------------------------------- */
    async search(query, opts = {}) {
      if (!this.pdfDoc || !query) {
        this._clearSearchHighlights();
        this.searchQuery   = '';
        this.searchMatches = [];
        this.searchIdx     = -1;
        this._pageTextCache = {};
        this._updateSearchCount();
        return;
      }

      this.searchQuery   = query;
      this.searchMatches = [];
      this.searchIdx     = -1;
      this._pageTextCache = {};

      this._clearSearchHighlights();

      const flags = 'gi';
      const pat   = this._escapeRe(query);

      // Build match list — per-item segment info for accurate highlight positioning
      for (let p = 1; p <= this.totalPages; p++) {
        const page = await this.pdfDoc.getPage(p);
        const tc   = await page.getTextContent();
        const items = tc.items.filter(i => typeof i.str === 'string');

        // Build cumulative char offsets and joined string
        const cumOffsets = [];
        let cum = 0;
        for (const item of items) { cumOffsets.push(cum); cum += item.str.length; }
        const joined = items.map(i => i.str).join('');

        this._pageTextCache[p] = { items, cumOffsets, joined };

        const re = new RegExp(pat, flags);
        let m;
        while ((m = re.exec(joined)) !== null) {
          const globalIdx = this.searchMatches.length;
          const segs = this._matchToSegments(items, cumOffsets, m.index, m.index + m[0].length);
          this.searchMatches.push({ page: p, segs, globalIdx });
        }
      }

      this._updateSearchCount();
      if (this.searchMatches.length > 0) {
        this.searchIdx = 0;
        this._jumpToMatch(0);
      } else {
        this.toast('No matches found');
      }

      // Highlight all currently-rendered pages
      this.pagesContainer.querySelectorAll('.pv-page-wrap').forEach(w => {
        this._highlightInPage(w);
      });
    }

    // Split a match [matchStart, matchEnd) in a joined string into per-item segments
    _matchToSegments(items, cumOffsets, matchStart, matchEnd) {
      const segs = [];
      for (let i = 0; i < items.length; i++) {
        const itemStart = cumOffsets[i];
        const itemEnd   = itemStart + items[i].str.length;
        if (itemEnd <= matchStart) continue;
        if (itemStart >= matchEnd)  break;
        segs.push({
          itemIdx:   i,
          charStart: Math.max(matchStart, itemStart) - itemStart,
          charEnd:   Math.min(matchEnd,   itemEnd)   - itemStart,
        });
      }
      return segs;
    }

    _escapeRe(s) { return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'); }

    _clearSearchHighlights() {
      this.pagesContainer.querySelectorAll('.pv-highlight-layer').forEach(hl => {
        hl.innerHTML = '';
      });
    }

    _highlightInPage(wrap) {
      if (!wrap._hlLayer) return;
      const pageNum = parseInt(wrap.dataset.page);
      const cache   = this._pageTextCache[pageNum];

      // Always clear first
      wrap._hlLayer.innerHTML = '';

      if (!this.searchQuery || !cache) return;

      const { items } = cache;
      const vp = wrap._vp;

      for (const match of this.searchMatches) {
        if (match.page !== pageNum) continue;

        for (const seg of match.segs) {
          const item = items[seg.itemIdx];
          if (!item || !item.str.length) continue;

          const fracStart = seg.charStart / item.str.length;
          const fracEnd   = seg.charEnd   / item.str.length;

          // Convert item origin to viewport pixel coords
          const [x0, y0] = vp.convertToViewportPoint(item.transform[4], item.transform[5]);
          // Right edge — gives us pixel width even when page is rotated
          const [x1]     = vp.convertToViewportPoint(
            item.transform[4] + item.width, item.transform[5]);

          const pixelWidth  = Math.abs(x1 - x0);
          const pixelHeight = Math.abs(item.height * vp.scale);

          // Fractional x-position along item direction
          const left   = Math.min(x0, x1) + fracStart * pixelWidth;
          const width  = (fracEnd - fracStart) * pixelWidth;
          const top    = y0 - pixelHeight;         // baseline → go up by height
          const height = pixelHeight * 1.15;       // slight extra to cover ascenders

          const div = document.createElement('div');
          div.className = 'pv-search-hl';
          div.style.cssText =
            `left:${left.toFixed(1)}px;top:${top.toFixed(1)}px;` +
            `width:${width.toFixed(1)}px;height:${height.toFixed(1)}px`;
          div.dataset.matchIdx = match.globalIdx;
          wrap._hlLayer.appendChild(div);
        }
      }
    }

    _jumpToMatch(idx) {
      if (!this.searchMatches.length) return;
      idx = ((idx % this.searchMatches.length) + this.searchMatches.length) % this.searchMatches.length;
      this.searchIdx = idx;
      const m = this.searchMatches[idx];
      this._updateSearchCount();

      // Remove previous active marker
      this.pagesContainer.querySelectorAll('.pv-search-hl.active')
        .forEach(d => d.classList.remove('active'));

      this.goToPage(m.page, true);

      setTimeout(() => {
        const pageWrap = this.pagesContainer.querySelector(
          `.pv-page-wrap[data-page="${m.page}"]`);
        if (!pageWrap) return;

        // Ensure highlights are drawn (page may have just been rendered)
        this._highlightInPage(pageWrap);

        const hlDivs = pageWrap.querySelectorAll(
          `.pv-search-hl[data-match-idx="${m.globalIdx}"]`);
        hlDivs.forEach(d => d.classList.add('active'));
        if (hlDivs[0]) hlDivs[0].scrollIntoView({ block: 'center', inline: 'nearest' });
      }, 300);
    }

    searchNext() { if (this.searchMatches.length) this._jumpToMatch(this.searchIdx + 1); }
    searchPrev() { if (this.searchMatches.length) this._jumpToMatch(this.searchIdx - 1); }

    _updateSearchCount() {
      if (!this.searchMatches.length) {
        this.searchCountEl.textContent = this.searchQuery ? '0 matches' : '';
      } else {
        this.searchCountEl.textContent = `${this.searchIdx + 1} / ${this.searchMatches.length}`;
      }
    }

    toggleSearch() {
      this.searchOpen = !this.searchOpen;
      this.searchBar.classList.toggle('open', this.searchOpen);
      this.btnSearch.classList.toggle('active', this.searchOpen);
      this.wrap.classList.toggle('search-active', this.searchOpen);
      if (this.searchOpen) this.searchInput.focus();
      else { this._clearSearchHighlights(); this.searchQuery = ''; }
    }

    /* ---------------------------------------------------
       Thumbnails
    --------------------------------------------------- */
    _buildThumbsGrid() {
      this.thumbsGrid.innerHTML = '';
      for (let i = 1; i <= this.totalPages; i++) {
        const item = el('div', 'pv-thumb-item' + (i === 1 ? ' active' : ''));
        item.dataset.page = i;

        const cWrap = el('div', 'pv-thumb-canvas-wrap');
        const canvas = el('canvas', 'pv-thumb-canvas');
        cWrap.appendChild(canvas);

        const lbl = el('span', 'pv-thumb-label', String(i));
        item.append(cWrap, lbl);
        this.thumbsGrid.appendChild(item);

        item.addEventListener('click', () => this.goToPage(i));

        // Lazy render thumbnails
        const io = new IntersectionObserver((entries) => {
          entries.forEach(e => {
            if (e.isIntersecting) {
              this._renderThumb(i, canvas);
              io.disconnect();
            }
          });
        }, { root: this.thumbsPanel });
        io.observe(item);
      }
    }

    async _renderThumb(pageNum, canvas) {
      if (!this.pdfDoc) return;
      try {
        const page = await this.pdfDoc.getPage(pageNum);
        const vp   = page.getViewport({ scale: 1 });
        const scale = this.opts.thumbSize / vp.width;
        const tvp  = page.getViewport({ scale });
        canvas.width  = tvp.width;
        canvas.height = tvp.height;
        await page.render({ canvasContext: canvas.getContext('2d'), viewport: tvp }).promise;
      } catch (e) { /* ignore */ }
    }

    _highlightActiveThumb(pageNum) {
      this.thumbsGrid.querySelectorAll('.pv-thumb-item').forEach(t => {
        t.classList.toggle('active', parseInt(t.dataset.page) === pageNum);
      });
      const active = this.thumbsGrid.querySelector('.pv-thumb-item.active');
      if (active && this.sidebarOpen) {
        active.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
      }
    }

    /* ---------------------------------------------------
       Outline / Bookmarks
    --------------------------------------------------- */
    async _loadOutline() {
      this.outlineList.innerHTML = '';
      if (!this.pdfDoc) return;

      let outline;
      try { outline = await this.pdfDoc.getOutline(); } catch (e) { outline = null; }

      if (!outline || !outline.length) {
        this.outlineList.innerHTML = `<li class="pv-outline-empty">No bookmarks</li>`;
        return;
      }

      this._buildOutlineTree(outline, this.outlineList);
    }

    _buildOutlineTree(items, parent) {
      items.forEach(item => {
        const li   = document.createElement('li');
        li.className = 'pv-outline-item';

        const link = el('div', 'pv-outline-link');

        if (item.items && item.items.length) {
          const tog = el('span', 'pv-outline-toggle open', ICONS.chevron);
          link.appendChild(tog);
          tog.addEventListener('click', (e) => {
            e.stopPropagation();
            tog.classList.toggle('open');
            childList.classList.toggle('open');
          });
        } else {
          const gap = el('span', '', '');
          gap.style.width = '16px';
          gap.style.display = 'inline-block';
          link.appendChild(gap);
        }

        const title = el('span', '', item.title || '(untitled)');
        title.style.flex = '1';
        link.appendChild(title);

        link.addEventListener('click', async () => {
          if (item.dest) {
            try {
              let dest = item.dest;
              if (typeof dest === 'string') dest = await this.pdfDoc.getDestination(dest);
              if (dest) {
                const ref = dest[0];
                const idx = await this.pdfDoc.getPageIndex(ref);
                this.goToPage(idx + 1);
              }
            } catch (e) { /* ignore */ }
          }
        });

        li.appendChild(link);

        if (item.items && item.items.length) {
          const childList = el('ul', 'pv-outline-children open');
          this._buildOutlineTree(item.items, childList);
          li.appendChild(childList);
        }

        parent.appendChild(li);
      });
    }

    /* ---------------------------------------------------
       Sidebar toggle
    --------------------------------------------------- */
    toggleSidebar() {
      this.sidebarOpen = !this.sidebarOpen;
      this.sidebar.classList.toggle('hidden', !this.sidebarOpen);
      this.btnSidebar.classList.toggle('active', this.sidebarOpen);
      // Show backdrop only when sidebar is an overlay drawer (mobile)
      if (this.sidebarBackdrop) {
        this.sidebarBackdrop.classList.toggle('visible', this.sidebarOpen && this._isMobile());
      }
      this.toast(this.sidebarOpen ? 'Sidebar open' : 'Sidebar closed');
      setTimeout(() => { if (this.pdfDoc) this._applyInitialZoom(); }, 250);
    }

    switchSidebarTab(tab) {
      this.sidebarTab = tab;
      this.tabThumbs.classList.toggle('active',  tab === 'thumbs');
      this.tabOutline.classList.toggle('active', tab === 'outline');
      this.thumbsPanel.classList.toggle('active',  tab === 'thumbs');
      this.outlinePanel.classList.toggle('active', tab === 'outline');
    }

    /* ---------------------------------------------------
       Dark mode
    --------------------------------------------------- */
    toggleDarkMode() {
      this.darkMode = !this.darkMode;
      this.wrap.classList.toggle('dark', this.darkMode);
      this.btnDark.innerHTML = this.darkMode ? ICONS.light : ICONS.dark;
      this.toast(this.darkMode ? 'Dark mode on' : 'Light mode on');
    }

    /* ---------------------------------------------------
       Fullscreen
    --------------------------------------------------- */
    toggleFullscreen() {
      if (!document.fullscreenElement) {
        this.wrap.requestFullscreen && this.wrap.requestFullscreen();
      } else {
        document.exitFullscreen && document.exitFullscreen();
      }
    }

    _onFullscreenChange() {
      this.isFullscreen = !!document.fullscreenElement;
      this.wrap.classList.toggle('fullscreen-mode', this.isFullscreen);
      this.btnFullscreen.innerHTML = this.isFullscreen ? ICONS.compress : ICONS.fullscreen;
      this.btnFullscreen.setAttribute('data-tip', this.isFullscreen ? 'Exit fullscreen (F)' : 'Fullscreen (F)');
      if (this.pdfDoc) setTimeout(() => this._applyInitialZoom(), 200);

      if (this.isFullscreen) {
        // Enter fullscreen — show controls so user can see them immediately.
        // Tapping the PDF content area will toggle them on/off.
        this.wrap.classList.add('fs-ui-visible');
      } else {
        // Exit fullscreen — always restore controls
        this.wrap.classList.remove('fs-ui-visible');
      }
    }

    // Toggle toolbar + bottom bar visibility with a single tap in fullscreen.
    _toggleFsUi() {
      this.wrap.classList.toggle('fs-ui-visible');
    }

    /* ---------------------------------------------------
       Two-page view
    --------------------------------------------------- */
    toggleTwoPage() {
      this.twoPage = !this.twoPage;
      this.pagesContainer.classList.toggle('two-page', this.twoPage);
      this.btnTwoPage.classList.toggle('active', this.twoPage);
      this.toast(this.twoPage ? 'Two-page view' : 'Single-page view');
    }

    /* ---------------------------------------------------
       Download
    --------------------------------------------------- */
    download() {
      if (!this._pdfUrl && !this._pdfBytes) { this.toast('No PDF loaded'); return; }
      const name = this.filenameEl.textContent || 'document.pdf';

      if (this._pdfUrl) {
        const a = document.createElement('a');
        a.href = this._pdfUrl;
        a.download = name;
        a.click();
      } else {
        const blob = new Blob([this._pdfBytes], { type: 'application/pdf' });
        const url  = URL.createObjectURL(blob);
        const a    = document.createElement('a');
        a.href = url; a.download = name; a.click();
        setTimeout(() => URL.revokeObjectURL(url), 5000);
      }
      this.toast('Downloading…');
    }

    /* ---------------------------------------------------
       Toast notifications
    --------------------------------------------------- */
    toast(msg) {
      const t = el('div', 'pv-toast', msg);
      this.toastWrap.appendChild(t);
      setTimeout(() => t.remove(), 2200);
    }

    /* ---------------------------------------------------
       Status bar
    --------------------------------------------------- */
    _updateStatusBar() {
      const pct = Math.round(this.zoom * 100);
      this.statusbarPage.textContent = this.pdfDoc
        ? `Page ${this.currentPage} of ${this.totalPages}` : '';
      this.statusbarZoom.textContent = `${pct}%`;
      this.statusbarMode.textContent = this.twoPage ? '2-page' : '';
    }

    /* ---------------------------------------------------
       Responsive helpers
    --------------------------------------------------- */
    _isMobile() {
      // Sidebar becomes a drawer when viewer width < 768px
      return this.wrap.offsetWidth < 768;
    }

    /* ---------------------------------------------------
       Loading / error
    --------------------------------------------------- */
    _showLoading(show) {
      this.loadingEl.classList.toggle('hidden', !show);
    }

    _setProgress(pct) {
      this._progressBar.style.width = pct + '%';
      this._loadingText.textContent = pct < 100 ? `Loading… ${pct}%` : 'Rendering…';
    }

    _showError(msg) {
      this._showLoading(false);
      this.toast('Error: ' + msg);
      console.error('[PDFViewer]', msg);
    }

    /* ---------------------------------------------------
       Keyboard shortcuts
    --------------------------------------------------- */
    _onKeyDown(e) {
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
      const ctrl = e.ctrlKey || e.metaKey;

      switch (e.key) {
        case 'ArrowLeft':  case 'ArrowUp':    e.preventDefault(); this.prevPage(); break;
        case 'ArrowRight': case 'ArrowDown':  e.preventDefault(); this.nextPage(); break;
        case 'Home': e.preventDefault(); this.firstPage(); break;
        case 'End':  e.preventDefault(); this.lastPage();  break;
        case 'f': case 'F':
          if (!ctrl) { e.preventDefault(); this.toggleFullscreen(); break; }
          e.preventDefault(); this.toggleSearch(); break;
        case 'd': case 'D': if (!ctrl) { e.preventDefault(); this.toggleDarkMode(); } break;
        case 's': case 'S': if (!ctrl) { e.preventDefault(); this.toggleSidebar(); } break;
        case 't': case 'T': if (!ctrl) { e.preventDefault(); this.toggleTwoPage(); } break;
        case 'r': e.preventDefault(); this.rotate(e.shiftKey ? -90 : 90); break;
        case 'R': e.preventDefault(); this.rotate(e.shiftKey ? -90 : 90); break;
        case '?':   e.preventDefault(); this._toggleShortcutsHelp(); break;
        case 'Escape':
          if (this._shortcutOpen) { this._toggleShortcutsHelp(); break; }
          if (this.searchOpen)    { this.toggleSearch(); break; }
          if (this.isFullscreen)  { document.exitFullscreen(); break; }
          break;
        case '+': case '=': if (ctrl) { e.preventDefault(); this.zoomIn(); } break;
        case '-':            if (ctrl) { e.preventDefault(); this.zoomOut(); } break;
        case '0':            if (ctrl) { e.preventDefault(); this.setZoom('fitWidth'); } break;
        case '1':            if (ctrl) { e.preventDefault(); this.setZoom('actual'); } break;
      }
    }

    _toggleShortcutsHelp() {
      this._shortcutOpen = !this._shortcutOpen;
      this.shortcutOverlay.classList.toggle('open', this._shortcutOpen);
    }

    /* ---------------------------------------------------
       Drag & drop
    --------------------------------------------------- */
    _onDragOver(e) {
      e.preventDefault();
      e.dataTransfer.dropEffect = 'copy';  // required by some browsers to allow drop
      this.dropOverlay.classList.add('active');
    }
    _onDragLeave(e) {
      // Only hide overlay when the drag truly leaves the viewer wrapper,
      // not when it moves between child elements inside it.
      if (e.relatedTarget && this.wrap.contains(e.relatedTarget)) return;
      this.dropOverlay.classList.remove('active');
    }
    _onDrop(e) {
      e.preventDefault();
      this.dropOverlay.classList.remove('active');
      const file = e.dataTransfer.files[0];
      if (!file) return;
      // Accept by MIME type OR by .pdf extension (some OS send empty MIME)
      const isPDF = file.type === 'application/pdf' || file.name.toLowerCase().endsWith('.pdf');
      if (isPDF) this.loadFile(file);
      else this.toast('Please drop a PDF file');
    }

    /* ---------------------------------------------------
       Mouse wheel zoom (Ctrl + scroll)
    --------------------------------------------------- */
    _onWheel(e) {
      if (!e.ctrlKey) return;
      e.preventDefault();
      if (e.deltaY < 0) this.zoomIn();
      else this.zoomOut();
    }

    /* ---------------------------------------------------
       Touch gestures (pinch-to-zoom)
    --------------------------------------------------- */
    _onTouchStart(e) {
      if (e.touches.length === 2) {
        this._pinchDist  = Math.hypot(
          e.touches[0].clientX - e.touches[1].clientX,
          e.touches[0].clientY - e.touches[1].clientY
        );
        this._pinchZoom  = this.zoom;
        this._pinchRatio = 1;

        // Midpoint relative to the scrollable viewport — used to correct scroll after zoom
        const vpRect        = this.viewport.getBoundingClientRect();
        this._pinchMidX     = (e.touches[0].clientX + e.touches[1].clientX) / 2 - vpRect.left;
        this._pinchMidY     = (e.touches[0].clientY + e.touches[1].clientY) / 2 - vpRect.top;
        this._pinchScrollX  = this.viewport.scrollLeft;
        this._pinchScrollY  = this.viewport.scrollTop;

        // Anchor CSS transform-origin to the same midpoint inside pagesContainer
        const pcRect = this.pagesContainer.getBoundingClientRect();
        const cx     = (e.touches[0].clientX + e.touches[1].clientX) / 2 - pcRect.left;
        const cy     = (e.touches[0].clientY + e.touches[1].clientY) / 2 - pcRect.top;
        this.pagesContainer.style.transformOrigin = `${cx}px ${cy}px`;
        this.pagesContainer.style.willChange      = 'transform';
      }
    }
    _onTouchMove(e) {
      if (e.touches.length === 2 && this._pinchDist) {
        e.preventDefault();
        const d     = Math.hypot(
          e.touches[0].clientX - e.touches[1].clientX,
          e.touches[0].clientY - e.touches[1].clientY
        );
        // Clamp so the visual scale stays within allowed zoom bounds
        const raw   = d / this._pinchDist;
        const minR  = 0.1  / this._pinchZoom;
        const maxR  = 4.0  / this._pinchZoom;
        this._pinchRatio = Math.max(minR, Math.min(maxR, raw));

        // GPU-accelerated CSS scale — instant visual feedback, zero re-render cost
        this.pagesContainer.style.transform = `scale(${this._pinchRatio})`;
      }
    }
    _onTouchEnd() {
      if (this._pinchDist) {
        const newZ  = Math.max(0.1, Math.min(this._pinchZoom * this._pinchRatio, 4.0));
        this.zoom   = newZ;
        const ratio = newZ / this._pinchZoom;

        // Compute new scroll so the pinch midpoint stays over the same content.
        // Formula: newScroll = (oldScroll + mid) * ratio - mid
        const newScrollLeft = (this._pinchScrollX + this._pinchMidX) * ratio - this._pinchMidX;
        const newScrollTop  = (this._pinchScrollY + this._pinchMidY) * ratio - this._pinchMidY;

        this._syncZoomSelect();
        this._updateStatusBar();

        // Phase 1 (sync): resize every page container to the new zoom while the CSS
        // scale is still active — layout settles before the browser paints anything.
        this._updatePageDimensions();

        // Phase 2 (next frame): clear the CSS scale + set scroll in a single RAF so
        // both happen atomically in the same paint, eliminating the brief jump.
        requestAnimationFrame(() => {
          this.pagesContainer.style.transform       = '';
          this.pagesContainer.style.transformOrigin = '';
          this.pagesContainer.style.willChange      = '';
          this.viewport.scrollLeft = newScrollLeft;
          this.viewport.scrollTop  = newScrollTop;
          this._triggerReRender();
        });

        this._pinchDist  = null;
        this._pinchRatio = 1;
      }
    }

    /* ---------------------------------------------------
       Context menu
    --------------------------------------------------- */
    _onContextMenu(e) {
      e.preventDefault();
      this.ctxMenu.style.left = e.clientX + 'px';
      this.ctxMenu.style.top  = e.clientY + 'px';
      this.ctxMenu.classList.add('open');
    }
    _closeCtxMenu() { this.ctxMenu.classList.remove('open'); }

    /* ---------------------------------------------------
       Resize observer
    --------------------------------------------------- */
    _initResize() {
      if (!window.ResizeObserver) return;
      this._applyLayout();
      this._resizeObs = new ResizeObserver(() => {
        this._applyLayout();
        // Only re-fit when the user's chosen mode is a fit mode — never override a manual zoom
        const mode = this._zoomMode || this._pendingZoom;
        if (this.pdfDoc && (mode === 'fitWidth' || mode === 'fitPage')) {
          clearTimeout(this._resizeTimer);
          this._resizeTimer = setTimeout(() => this._applyInitialZoom(), 250);
        }
        // If resized to desktop width, remove mobile backdrop
        if (this.sidebarBackdrop && !this._isMobile()) {
          this.sidebarBackdrop.classList.remove('visible');
        }
      });
      this._resizeObs.observe(this.wrap);
    }

    _applyLayout() {
      const mobile = this.wrap.offsetWidth <= 767;
      if (this._layoutMobile === mobile) return;
      this._layoutMobile = mobile;
      const all = [...this._bbGroup1, ...this._bbGroup2];
      if (mobile) {
        all.forEach(e => this.bottomBar.appendChild(e));
      } else {
        this._bbGroup1.forEach(e => this.toolbar.insertBefore(e, this._tbAnchor1));
        this._bbGroup2.forEach(e => this.toolbar.insertBefore(e, this._tbAnchor2));
      }
    }

    /* ---------------------------------------------------
       Event binding (single place)
    --------------------------------------------------- */
    _bindEvents() {
      // Toolbar buttons
      this.btnSidebar.addEventListener('click', () => this.toggleSidebar());
      this.btnOpen.addEventListener('click', () => {
        const inp = document.createElement('input');
        inp.type = 'file'; inp.accept = 'application/pdf';
        inp.addEventListener('change', () => { if (inp.files[0]) this.loadFile(inp.files[0]); });
        inp.click();
      });

      this.btnFirst.addEventListener('click', () => this.firstPage());
      this.btnPrev.addEventListener('click',  () => this.prevPage());
      this.btnNext.addEventListener('click',  () => this.nextPage());
      this.btnLast.addEventListener('click',  () => this.lastPage());

      this.pageInput.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') {
          const n = parseInt(this.pageInput.value);
          if (!isNaN(n)) this.goToPage(n);
        }
      });
      this.pageInput.addEventListener('blur', () => {
        const n = parseInt(this.pageInput.value);
        if (!isNaN(n)) this.goToPage(n);
      });

      this.btnZoomIn.addEventListener('click',  () => this.zoomIn());
      this.btnZoomOut.addEventListener('click', () => this.zoomOut());
      this.zoomSelect.addEventListener('change', () => this.setZoom(this.zoomSelect.value));

      this.btnSearch.addEventListener('click', () => this.toggleSearch());
      this.searchInput.addEventListener('input', () => this.search(this.searchInput.value));
      this.searchInput.addEventListener('keydown', (e) => {
        if (e.key === 'Enter') { e.shiftKey ? this.searchPrev() : this.searchNext(); }
        if (e.key === 'Escape') { this.toggleSearch(); }
      });
      this._searchPrev.addEventListener('click',  () => this.searchPrev());
      this._searchNext.addEventListener('click',  () => this.searchNext());
      this._searchClose.addEventListener('click', () => this.toggleSearch());

      this.btnRotL.addEventListener('click', () => this.rotate(-90));
      this.btnRotR.addEventListener('click', () => this.rotate(90));
      this.btnTwoPage.addEventListener('click', () => this.toggleTwoPage());
      this.btnFitW.addEventListener('click', () => this.setZoom('fitWidth'));

      this.btnDark.addEventListener('click', () => this.toggleDarkMode());
      this.btnFullscreen.addEventListener('click', () => this.toggleFullscreen());
      this.btnKeyboard.addEventListener('click', () => this._toggleShortcutsHelp());

      // Sidebar tabs
      this.tabThumbs.addEventListener('click',   () => this.switchSidebarTab('thumbs'));
      this.tabOutline.addEventListener('click',  () => this.switchSidebarTab('outline'));

      // File input (empty state)
      if (this._fileInput) {
        this._fileInput.addEventListener('change', () => {
          if (this._fileInput.files[0]) this.loadFile(this._fileInput.files[0]);
        });
      }

      // Viewport scroll
      this.viewport.addEventListener('scroll', () => this._onViewportScroll());

      // Scroll indicator drag
      this._bindScrollIndicatorDrag();

      // Drag & drop
      if (this.opts.enableDrop) {
        this.wrap.addEventListener('dragover',  (e) => this._onDragOver(e));
        this.wrap.addEventListener('dragleave', (e) => this._onDragLeave(e));
        this.wrap.addEventListener('drop',      (e) => this._onDrop(e));
      }

      // Wheel zoom
      this.viewport.addEventListener('wheel', (e) => this._onWheel(e), { passive: false });

      // Touch pinch
      this.viewport.addEventListener('touchstart', (e) => this._onTouchStart(e));
      this.viewport.addEventListener('touchmove',  (e) => this._onTouchMove(e),  { passive: false });
      this.viewport.addEventListener('touchend',   () => this._onTouchEnd());

      // Context menu
      this.pagesContainer.addEventListener('contextmenu', (e) => this._onContextMenu(e));
      document.addEventListener('click', () => this._closeCtxMenu());
      this.ctxMenu.querySelectorAll('.pv-ctx-item').forEach(item => {
        item.addEventListener('click', () => {
          const action = item.dataset.action;
          this._closeCtxMenu();
        });
      });

      // Fullscreen events
      document.addEventListener('fullscreenchange', () => this._onFullscreenChange());

      // Fullscreen tap-to-toggle: tap the PDF content area to show/hide controls
      this.viewport.addEventListener('click', () => { if (this.isFullscreen) this._toggleFsUi(); });

      // Keyboard
      if (this.opts.enableKeyboard) {
        document.addEventListener('keydown', (e) => {
          // only handle if viewer is focused or active
          if (this.wrap.contains(document.activeElement) || document.activeElement === document.body) {
            this._onKeyDown(e);
          }
        });
      }

      // Shortcuts overlay close
      const closeBtn = this.shortcutOverlay.querySelector('#pv-close-shortcuts');
      if (closeBtn) closeBtn.addEventListener('click', () => this._toggleShortcutsHelp());
      this.shortcutOverlay.addEventListener('click', (e) => {
        if (e.target === this.shortcutOverlay) this._toggleShortcutsHelp();
      });

      // Resize
      this._initResize();
    }

    /* ---------------------------------------------------
       Destroy
    --------------------------------------------------- */
    destroy() {
      this._resizeObs && this._resizeObs.disconnect();
      this._ioObserver && this._ioObserver.disconnect();
      this.ctxMenu.remove();
      this.wrap.remove();
    }
  }

  /* -------------------------------------------------------
     Expose globally
  ------------------------------------------------------- */
  global.AdvancedPDFViewer = AdvancedPDFViewer;

})(typeof window !== 'undefined' ? window : this);
